import json
import random
from datetime import datetime, timezone
from agents.base_agent import call_glm
from prompts.agent5_prompt import REPORTER_PROMPT


async def generate_report(
    deposit_profile: dict,
    flowsheet: dict,
    compliance: dict,
    historical_context: dict,
) -> dict:
    """
    Agent 5 — The Report Writer (Priority 3)

    Synthesises all agent outputs into a clean, professional
    engineering report readable by site engineers and government managers.
    Output is bilingual: Bahasa Malaysia + English.
    """

    report_id = _generate_report_id()

    message = f"""
REPORT ID: {report_id}
GENERATED: {datetime.now(timezone.utc).isoformat()}

DEPOSIT PROFILE
===============
{json.dumps(deposit_profile, indent=2)}

HISTORICAL CONTEXT (from Agent 1)
==================================
Cases found : {historical_context.get('cases_found', 0)}
Summary     : {historical_context.get('summary', 'N/A')}

RECOMMENDED FLOWSHEET (from Agent 2)
======================================
{json.dumps(flowsheet, indent=2)}

COMPLIANCE RESULT (from Agent 4)
==================================
Overall status    : {compliance.get('overall_status', 'unknown')}
Critical failures : {compliance.get('critical_failures', 0)}
Warnings          : {compliance.get('warnings', 0)}
Checks            :
{json.dumps(compliance.get('checks', []), indent=2)}

TASK
====
Write the full engineering report synthesising all the above.
The report_id is {report_id}.
Output valid JSON matching the specified schema.
Write executive summaries in plain language — no jargon.
"""

    result = await call_glm(
        system_prompt=REPORTER_PROMPT,
        user_message=message,
        json_mode=True,
    )

    try:
        report = json.loads(result["output"])
        report["report_id"] = report_id  # Ensure ID is correct
        return report
    except (json.JSONDecodeError, KeyError):
        # Fallback: assemble minimal report manually
        return _build_fallback_report(
            report_id, deposit_profile, flowsheet, compliance
        )


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _generate_report_id() -> str:
    date_str = datetime.now(timezone.utc).strftime("%Y%m%d")
    suffix   = random.randint(1000, 9999)
    return f"EM-{date_str}-{suffix}"


def _build_fallback_report(
    report_id: str,
    deposit_profile: dict,
    flowsheet: dict,
    compliance: dict,
) -> dict:
    """Returns a minimal valid report if GLM JSON parsing fails."""
    return {
        "report_id":             report_id,
        "generated_at":          datetime.now(timezone.utc).isoformat(),
        "executive_summary_bm":  "Laporan dijana oleh Zync. Semak parameter di bawah.",
        "executive_summary_en":  "Report generated by Zync. Review parameters below.",
        "deposit_summary": {
            "location":  deposit_profile.get("location", "Unknown"),
            "clay_type": deposit_profile.get("clay_type", "Unknown"),
            "ree_grade": deposit_profile.get("ree_grade", "Unknown"),
            "state":     deposit_profile.get("state", "Unknown"),
        },
        "historical_context": {
            "cases_used":  0,
            "key_insight": "Insufficient historical data.",
        },
        "recommended_flowsheet": {
            "lixiviant":          flowsheet.get("lixiviant", "Unknown"),
            "concentration_M":    flowsheet.get("concentration_M", 0),
            "pH_range":           flowsheet.get("pH_range", "Unknown"),
            "temperature_C":      flowsheet.get("temperature_C", 0),
            "contact_time_hrs":   flowsheet.get("contact_time_hrs", 0),
            "predicted_yield_pct": flowsheet.get("predicted_yield_pct", 0),
            "sfiles_string":      flowsheet.get("sfiles_string", ""),
            "reasoning_summary":  "See reasoning block for full details.",
        },
        "compliance": {
            "overall_status":   compliance.get("overall_status", "unknown"),
            "critical_failures": compliance.get("critical_failures", 0),
            "checks_summary":   compliance.get("summary_en", ""),
        },
        "risks": {
            "thorium_risk":       flowsheet.get("thorium_risk", "unknown"),
            "thorium_mitigation": flowsheet.get("thorium_risk_reason", ""),
            "esg_flags":          [flowsheet.get("esg_note", "")] if flowsheet.get("esg_flag") else [],
        },
        "next_steps": [
            "Conduct laboratory leaching test with recommended parameters",
            "Submit EIA application to DOE before site operations",
            "Register site with AELB for radioactivity monitoring",
            "Install pH and temperature sensors for real-time monitoring",
        ],
        "confidence": flowsheet.get("confidence", "low"),
    }